# Generated by Django 3.0.3 on 2020-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/images/default.jpg', upload_to='blog/images/'),
        ),
    ]
